name: .NET Core Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted]
    container: 
      image: mcr.microsoft.com/devcontainers/dotnet:1-8.0

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore